-- Insert sample Authors
INSERT INTO author (name, date_of_birth) VALUES ('John Doe', '1970-01-01');
INSERT INTO author (name, date_of_birth) VALUES ('Jane Smith', '1980-02-02');
INSERT INTO author (name, date_of_birth) VALUES ('Emily Johnson', '1975-03-03');
INSERT INTO author (name, date_of_birth) VALUES ('Michael Brown', '1965-04-04');
INSERT INTO author (name, date_of_birth) VALUES ('Jessica Davis', '1985-05-05');
INSERT INTO author (name, date_of_birth) VALUES ('David Wilson', '1970-06-06');
INSERT INTO author (name, date_of_birth) VALUES ('Sarah Miller', '1990-07-07');
INSERT INTO author (name, date_of_birth) VALUES ('James Martinez', '1982-08-08');
INSERT INTO author (name, date_of_birth) VALUES ('Laura Anderson', '1978-09-09');
INSERT INTO author (name, date_of_birth) VALUES ('Robert Taylor', '1968-10-10');
INSERT INTO author (name, date_of_birth) VALUES ('Linda Thomas', '1983-11-11');
INSERT INTO author (name, date_of_birth) VALUES ('William Moore', '1972-12-12');
INSERT INTO author (name, date_of_birth) VALUES ('Barbara Jackson', '1981-01-13');
INSERT INTO author (name, date_of_birth) VALUES ('Richard White', '1977-02-14');
INSERT INTO author (name, date_of_birth) VALUES ('Susan Harris', '1988-03-15');
INSERT INTO author (name, date_of_birth) VALUES ('Joseph Martin', '1969-04-16');
INSERT INTO author (name, date_of_birth) VALUES ('Karen Lee', '1976-05-17');
INSERT INTO author (name, date_of_birth) VALUES ('Charles Young', '1984-06-18');
INSERT INTO author (name, date_of_birth) VALUES ('Patricia Walker', '1991-07-19');
INSERT INTO author (name, date_of_birth) VALUES ('Thomas Hall', '1980-08-20');
INSERT INTO author (name, date_of_birth) VALUES ('Jennifer Allen', '1974-09-21');
INSERT INTO author (name, date_of_birth) VALUES ('Daniel Hernandez', '1987-10-22');
INSERT INTO author (name, date_of_birth) VALUES ('Mary King', '1971-11-23');
INSERT INTO author (name, date_of_birth) VALUES ('Matthew Wright', '1982-12-24');
INSERT INTO author (name, date_of_birth) VALUES ('Elizabeth Scott', '1979-01-25');
INSERT INTO author (name, date_of_birth) VALUES ('Mark Green', '1986-02-26');
INSERT INTO author (name, date_of_birth) VALUES ('Nancy Adams', '1973-03-27');
INSERT INTO author (name, date_of_birth) VALUES ('Steven Baker', '1966-04-28');
INSERT INTO author (name, date_of_birth) VALUES ('Lisa Nelson', '1992-05-29');
INSERT INTO author (name, date_of_birth) VALUES ('Anthony Carter', '1985-06-30');

-- Insert sample Books
INSERT INTO book (title, genre, price, author_id) VALUES ('Spring Boot in Action', 'Technology', 29.99, 1);
INSERT INTO book (title, genre, price, author_id) VALUES ('Hibernate in Practice', 'Technology', 39.99, 1);
INSERT INTO book (title, genre, price, author_id) VALUES ('Effective Java', 'Technology', 49.99, 2);
INSERT INTO book (title, genre, price, author_id) VALUES ('Clean Code', 'Technology', 34.99, 3);
INSERT INTO book (title, genre, price, author_id) VALUES ('Java Concurrency in Practice', 'Technology', 45.99, 3);
INSERT INTO book (title, genre, price, author_id) VALUES ('Design Patterns', 'Technology', 42.99, 4);
INSERT INTO book (title, genre, price, author_id) VALUES ('Refactoring', 'Technology', 37.99, 5);
INSERT INTO book (title, genre, price, author_id) VALUES ('Head First Java', 'Technology', 29.99, 6);
INSERT INTO book (title, genre, price, author_id) VALUES ('The Pragmatic Programmer', 'Technology', 39.99, 7);
INSERT INTO book (title, genre, price, author_id) VALUES ('Code Complete', 'Technology', 49.99, 8);
INSERT INTO book (title, genre, price, author_id) VALUES ('Introduction to Algorithms', 'Technology', 59.99, 9);
INSERT INTO book (title, genre, price, author_id) VALUES ('You Know JS', 'Technology', 29.99, 10);
INSERT INTO book (title, genre, price, author_id) VALUES ('Eloquent JavaScript', 'Technology', 34.99, 11);
INSERT INTO book (title, genre, price, author_id) VALUES ('Learning Python', 'Technology', 45.99, 12);
INSERT INTO book (title, genre, price, author_id) VALUES ('Automate the Boring Stuff with Python', 'Technology', 37.99, 13);
INSERT INTO book (title, genre, price, author_id) VALUES ('Fluent Python', 'Technology', 49.99, 14);
INSERT INTO book (title, genre, price, author_id) VALUES ('Python Crash Course', 'Technology', 29.99, 15);
INSERT INTO book (title, genre, price, author_id) VALUES ('Python for Data Analysis', 'Technology', 39.99, 16);
INSERT INTO book (title, genre, price, author_id) VALUES ('Cracking the Coding Interview', 'Technology', 45.99, 17);
INSERT INTO book (title, genre, price, author_id) VALUES ('Groovy in Action', 'Technology', 37.99, 18);
INSERT INTO book (title, genre, price, author_id) VALUES ('JavaScript: The Good Parts', 'Technology', 29.99, 19);
INSERT INTO book (title, genre, price, author_id) VALUES ('Node.js Design Patterns', 'Technology', 39.99, 20);
INSERT INTO book (title, genre, price, author_id) VALUES ('Pro Git', 'Technology', 45.99, 21);
INSERT INTO book (title, genre, price, author_id) VALUES ('Continuous Delivery', 'Technology', 37.99, 22);
INSERT INTO book (title, genre, price, author_id) VALUES ('Test-Driven Development', 'Technology', 49.99, 23);
INSERT INTO book (title, genre, price, author_id) VALUES ('Building Microservices', 'Technology', 29.99, 24);
INSERT INTO book (title, genre, price, author_id) VALUES ('Site Reliability Engineering', 'Technology', 39.99, 25);
INSERT INTO book (title, genre, price, author_id) VALUES ('Microservices Patterns', 'Technology', 45.99, 26);
INSERT INTO book (title, genre, price, author_id) VALUES ('Kubernetes Up & Running', 'Technology', 37.99, 27);
INSERT INTO book (title, genre, price, author_id) VALUES ('Docker in Action', 'Technology', 49.99, 28);
INSERT INTO book (title, genre, price, author_id) VALUES ('Kafka: The Definitive Guide', 'Technology', 29.99, 29);
INSERT INTO book (title, genre, price, author_id) VALUES ('Mastering Spring Boot', 'Technology', 39.99, 30);

-- Insert sample Members
INSERT INTO member (username, email, address, phone_number) VALUES ('johndoe', 'johndoe@example.com', '123 Main St', '123-456-7890');
INSERT INTO member (username, email, address, phone_number) VALUES ('janesmith', 'janesmith@example.com', '456 Elm St', '987-654-3210');
INSERT INTO member (username, email, address, phone_number) VALUES ('michaeljohnson', 'michaeljohnson@example.com', '789 Pine St', '456-789-0123');
INSERT INTO member (username, email, address, phone_number) VALUES ('emilybrown', 'emilybrown@example.com', '321 Oak St', '654-321-0987');
INSERT INTO member (username, email, address, phone_number) VALUES ('davidwilson', 'davidwilson@example.com', '654 Maple St', '321-654-9870');
INSERT INTO member (username, email, address, phone_number) VALUES ('jessicamiller', 'jessicamiller@example.com', '987 Cedar St', '789-012-3456');
INSERT INTO member (username, email, address, phone_number) VALUES ('sarahmartinez', 'sarahmartinez@example.com', '543 Birch St', '012-345-6789');
INSERT INTO member (username, email, address, phone_number) VALUES ('jamesanderson', 'jamesanderson@example.com', '876 Walnut St', '210-987-6543');
INSERT INTO member (username, email, address, phone_number) VALUES ('laurataylor', 'laurataylor@example.com', '109 Spruce St', '678-543-2109');
INSERT INTO member (username, email, address, phone_number) VALUES ('robertthomas', 'robertthomas@example.com', '210 Fir St', '345-678-9012');
INSERT INTO member (username, email, address, phone_number) VALUES ('lindamoore', 'lindamoore@example.com', '321 Chestnut St', '987-654-3210');
INSERT INTO member (username, email, address, phone_number) VALUES ('williamjackson', 'williamjackson@example.com', '432 Ash St', '456-789-0123');
INSERT INTO member (username, email, address, phone_number) VALUES ('barbarawhite', 'barbarawhite@example.com', '543 Redwood St', '654-321-0987');
INSERT INTO member (username, email, address, phone_number) VALUES ('richardharris', 'richardharris@example.com', '654 Willow St', '321-654-9870');
INSERT INTO member (username, email, address, phone_number) VALUES ('susanmartin', 'susanmartin@example.com', '765 Dogwood St', '789-012-3456');
INSERT INTO member (username, email, address, phone_number) VALUES ('josephlee', 'josephlee@example.com', '876 Cherry St', '012-345-6789');
INSERT INTO member (username, email, address, phone_number) VALUES ('karenyoung', 'karenyoung@example.com', '987 Poplar St', '210-987-6543');
INSERT INTO member (username, email, address, phone_number) VALUES ('charleswalker', 'charleswalker@example.com', '109 Cypress St', '678-543-2109');
INSERT INTO member (username, email, address, phone_number) VALUES ('patriciahall', 'patriciahall@example.com', '210 Palm St', '345-678-9012');
INSERT INTO member (username, email, address, phone_number) VALUES ('thomasallen', 'thomasallen@example.com', '321 Sequoia St', '987-654-3210');
INSERT INTO member (username, email, address, phone_number) VALUES ('jenniferhernandez', 'jenniferhernandez@example.com', '432 Sycamore St', '456-789-0123');
INSERT INTO member (username, email, address, phone_number) VALUES ('danielking', 'danielking@example.com', '543 Magnolia St', '654-321-0987');
INSERT INTO member (username, email, address, phone_number) VALUES ('marywright', 'marywright@example.com', '654 Holly St', '321-654-9870');
INSERT INTO member (username, email, address, phone_number) VALUES ('matthewscott', 'matthewscott@example.com', '765 Pineapple St', '789-012-3456');
INSERT INTO member (username, email, address, phone_number) VALUES ('elizabethgreen', 'elizabethgreen@example.com', '876 Grapevine St', '012-345-6789');
INSERT INTO member (username, email, address, phone_number) VALUES ('markadams', 'markadams@example.com', '987 Blueberry St', '210-987-6543');
INSERT INTO member (username, email, address, phone_number) VALUES ('nancybaker', 'nancybaker@example.com', '109 Raspberry St', '678-543-2109');
INSERT INTO member (username, email, address, phone_number) VALUES ('stevennelson', 'stevennelson@example.com', '210 Blackberry St', '345-678-9012');
INSERT INTO member (username, email, address, phone_number) VALUES ('lisacarter', 'lisacarter@example.com', '321 Strawberry St', '987-654-3210');
INSERT INTO member (username, email, address, phone_number) VALUES ('anthonycarter', 'anthonycarter@example.com', '432 Peach St', '456-789-0123');

-- Insert sample Loans
INSERT INTO loan (book_id, member_id, lend_date, return_date) VALUES (1, 1, '2023-07-01', '2023-07-15');
INSERT INTO loan (book_id, member_id, lend_date, return_date) VALUES (2, 2, '2023-07-05', '2023-07-20');
INSERT INTO loan (book_id, member_id, lend_date, return_date) VALUES (3, 2, '2023-07-10', NULL);
INSERT INTO loan (book_id, member_id, lend_date, return_date) VALUES (4, 3, '2023-07-01', '2023-07-10');
INSERT INTO loan (book_id, member_id, lend_date, return_date) VALUES (5, 4, '2023-07-05', '2023-07-15');
INSERT INTO loan (book_id, member_id, lend_date, return_date) VALUES (6, 5, '2023-07-08', '2023-07-18');
INSERT INTO loan (book_id, member_id, lend_date, return_date) VALUES (7, 6, '2023-07-10', '2023-07-20');
INSERT INTO loan (book_id, member_id, lend_date, return_date) VALUES (8, 7, '2023-07-12', '2023-07-22');
INSERT INTO loan (book_id, member_id, lend_date, return_date) VALUES (9, 8, '2023-07-14', '2023-07-24');
INSERT INTO loan (book_id, member_id, lend_date, return_date) VALUES (10, 9, '2023-07-16', '2023-07-26');
